import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./src/components/providers/Query.Provider";
import ReduxProvider from "./src/components/providers/Redux.Provider";

import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Crypto Trading Simulator",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>

        <body
          className={`${poppins.variable} ${roboto.variable} antialiased`}
        >



          <ReduxProvider>
            {children}
            <Toaster />
          </ReduxProvider>


        </body>

      </Providers>

    </html>
  );
}
